# Generated by Django 5.2.4 on 2025-07-23 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('product_type', models.CharField(choices=[('saree', 'Saree'), ('shirt', 'Shirt'), ('dhothi', 'Dhothi')], max_length=20)),
                ('fabric_type', models.CharField(blank=True, max_length=100)),
                ('color_preferences', models.JSONField(blank=True, null=True)),
                ('color_reference_image', models.ImageField(blank=True, null=True, upload_to='color_refs/')),
                ('style_pattern', models.CharField(blank=True, max_length=100)),
                ('sample_design', models.ImageField(blank=True, null=True, upload_to='design_samples/')),
                ('size', models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=10)),
                ('size_chart', models.FileField(blank=True, null=True, upload_to='size_charts/')),
                ('brand_label', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField()),
                ('preferred_delivery_date', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_instructions', models.TextField(blank=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
